### ISSUE TITLE
🐛 README License Badge

### ISSUE THREAD

**Issue by JoeKarow** [JoeKarow/netwerkr#24]
## Bug Report

**netwerkr version:**

**Current behavior:** License Badge shows 'not identifiable by github'

**Expected behavior:** License Badge should show GPLv3

**Steps to reproduce:** View repo README

**Related code:** README.md

**Other information:**

**Comment by JoeKarow** [comment]
Creating issue to attach to PR#23, courtesy of @rahulkarda

**Comment by rahulkarda** [comment]
Should I close this PR?

**Comment by JoeKarow** [comment]
Nope! I just added this issue as a lil bit of housekeeping. You get merged!

Thanks again!
